package com.todorhryn.skyblox.game;

public enum LevelEditorState {
    DO_NOTHING, ADD_NEW_TILE, SELECT_TILE, SELECT_CONTROLLED_TILES, MOVE_PLAYER, SELECT_MAIN_BLOCK_POSITION, SELECT_SECOND_BLOCK_POSITION
}
